# Generated by Django 3.1.5 on 2021-01-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_no', models.CharField(max_length=50, unique=True)),
                ('device_id', models.IntegerField(unique=True)),
                ('bike_status', models.IntegerField()),
                ('last_full_maintainance_date', models.DateField()),
            ],
        ),
    ]
