# Generated by Django 3.1.5 on 2021-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='device_id',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
