# Generated by Django 3.1.5 on 2021-02-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='salary',
            field=models.IntegerField(default=5000),
        ),
    ]
