# Generated by Django 3.1.5 on 2021-02-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='salary',
        ),
    ]
